### ISSUE TITLE
Incomplete description

### ISSUE THREAD

**Issue by Lui22** [MattBidewell/min-content-max-content-bug#1]
What outputs your browsers display?

Win10, FF 107, Chrome 106.
Both displays 150px × 150px image

**Comment by MattBidewell** [comment]
@Lui22 Cheers, for looking on Windows as well.

It seems to be only effecting Safari/WebKit based browsers. The output on Safari is 850pxx850px. 

I've updated the ReadMe.

**Comment by Lui22** [comment]
Imo it would be worth adding example images as well
